### ISSUE TITLE
Installation not working: invalid schema, class not found

### ISSUE THREAD

**Issue by Schrigga** [apioo/fusio-sample-cms#6]
I have checked out the git and followed the instructions. 

It would be great to mention in the instructions that before executing `php bin/fusio deploy` you need to login `php bin/fusio auth:login`. Additionally it would be great to mention the default password for the Administrator account. 

During the deploy the following message occurs: 

```
- [FAILED] config scopes_default: Provided an invalid schema Fusio\Model\Backend\Config_Create, got: Schema Fusio\Model\Backend\Config_Create does not exist
```

I have ignored the message and continued with serving the public folder. Then the following message occurs: 

```
[500]: OPTIONS //index.php/authorization/token - Uncaught Error: Class "PSX\Framework\Environment\WebServer\Engine" not found
```

I use MariaDB 10.7.1with PHP 8.0.14.

**Comment by chriskapp** [comment]
Hi, yes so I have just updated the readme and also the code base. The error regarding the config is only since the setting does not longer exist. Regarding the Engine error it looks like you have not run `composer install` to install all dependencies, but I have now also added this step to the readme.

**Comment by Schrigga** [comment]
I have pulled the changes and have rerun `composer install` but the error about `PSX\Framework\Environment\WebServer\Engine` still exists. 

The file is mentioned in the `public/index.php` but looking at the folder `vendor/psx/framework/src/Environment` does not contain a folder WebServer. There is just a folder CLI which also contains a class Engine. Probably the reference in the `index.php` is wrong or the wrong version of psx/framework is installed through composer (v.5.1.0).

**Comment by chriskapp** [comment]
ok, the index has changed in a later version but I have just updated it to the current version so please check whether this works now as expected.

**Comment by Schrigga** [comment]
Now it works. Thanks a lot :)
